---
version: '1.0'
output-on-error:
  error: Error condition
input:
  - items:
      - foo
      - bar
tasks:
  random_task:
    pause-before: yes
    with:
      items: i in <% ctx().items %>
      concurrency: 4
    action: core.noop
    retry:
      count: 15
      delay: 4
